#!/bin/bash
clear

# Load environment variables from .env file
export $(grep -v '^#' .env | xargs)

# Run the roc commands with the environment variable
DATABASE_URL="$DATABASE_URL" bun x dbmate up && roc check ./src/Main.roc && roc format && roc test ./src/Main.roc && DATABASE_URL="$DATABASE_URL" TMDB_API_READ_ACCESS_TOKEN="$TMDB_API_READ_ACCESS_TOKEN" roc run ./src/Main.roc
